args:
  log_dir: logs
  adv_batch_size: 2
  adv_eps: 0.062745098
  classifier_name: celebahq__Eyeglasses
  config: celeba.yml
  data_seed: 5
  diffusion_type: ddpm
  domain: celebahq
  eot_attack_reps: 15
  eot_defense_reps: 20
  eot_iter: 20
  exp: ./exp_results
  image_folder: ./exp_results/celebahq-adv-500-eps0.062745098-2x4-disc-bpda-rev
  ni: false
  num_sub: 1000
  partition: val
  rand_t: false
  sample_step: 1
  score_type: guided_diffusion
  seed: 122
  t: 500
  t_delta: 15
  use_bm: false
  verbose: info
config:
  data:
    category: cifar10
    centered: true
    dataset: CIFAR10
    image_size: 32
    num_channels: 3
    random_flip: true
    uniform_dequantization: false
  device: cuda
  image_size: 64
  model:
    attention_type: ddpm
    attn_resolutions:
    - 16
    beta_max: 20.0
    beta_min: 0.1
    ch_mult:
    - 1
    - 2
    - 2
    - 2
    conditional: true
    conv_size: 3
    dropout: 0.1
    ema_rate: 0.9999
    embedding_type: positional
    fir: false
    fir_kernel:
    - 1
    - 3
    - 3
    - 1
    fourier_scale: 16
    init_scale: 0.0
    name: ncsnpp
    nf: 128
    nonlinearity: swish
    normalization: GroupNorm
    num_res_blocks: 8
    num_scales: 1000
    progressive: none
    progressive_combine: sum
    progressive_input: none
    resamp_with_conv: true
    resblock_type: biggan
    scale_by_sigma: false
    sigma_max: 50
    sigma_min: 0.01
    skip_rescale: true
  num_channels: 3
  optim:
    beta1: 0.9
    eps: 1.0e-08
    grad_clip: 1.0
    lr: 0.0002
    optimizer: Adam
    warmup: 5000
    weight_decay: 0
  sampling:
    corrector: none
    method: pc
    n_steps_each: 1
    noise_removal: true
    predictor: euler_maruyama
    probability_flow: false
    snr: 0.16
  training:
    continuous: true
    n_iters: 950001
    reduce_mean: true
    sde: vpsde
